### ISSUE TITLE
Have suites and tests execute in order

### ISSUE THREAD

**Issue by markasoftware** [jrfeenst/jstestr#1]
I want to be able to have certain tests always execute before other ones, because I'm planning to have some tests rely on the output of other tests. I notice that the tests in jstestr execute in whatever order they load in, however, which doesn't work to well. The suites seem to run in effectively random order as well. Could you provide a way to guarantee that certain tests execute before others? I'll probably start working on this feature myself soon, but if you can probably get it done faster, so it'd be appreciated if you'll get this working soon

**Comment by jrfeenst** [comment]
I really don't think it's a good idea for tests to be order dependant. It makes things like rerunning a particular test point very difficult. Tests shouldn't leave state around which may affect other tests when they are done. If one test fails then the others would probably fail, so it's probably best to just combine them into 1 test or use suite setup or a helper function to initialize things separately for each test.
